name: Update JSON File

on:
  repository_dispatch:
    types: [update_json]

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install jq
        run: sudo apt-get install jq

      - name: Read and Update JSON
        run: |
          FILE="data.json"
          NEW_DATA='${{ github.event.client_payload }}'

          # Ensure the JSON file exists
          if [ ! -f "$FILE" ]; then
            echo "[]" > "$FILE"
          fi

          # Append the new data
          jq ". += [$NEW_DATA]" "$FILE" > tmp.json && mv tmp.json "$FILE"

      - name: Commit & Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data.json
          git commit -m "Updated data.json with new entry" || echo "No changes to commit"
          git push
